### ISSUE TITLE
What's the reason for not adding ^ and $ by default?

### ISSUE THREAD

**Issue by rkrx** [baryshev/TreeRoute#3]
What's the reason for not adding ^ and $ by default?

https://github.com/baryshev/TreeRoute/blob/master/src/Router.php#L27

**Comment by baryshev** [comment]
In the first version i added ^ and $, but removed it later to take a full control above the param regexp. Thinking about settings: enable or disable this feature.

**Comment by rkrx** [comment]
Can you explain, why you removed that later? I can't imagine in what situation this makes sense...

**Comment by baryshev** [comment]
There is only difference between with `^ and $` by default and without it.
**With**: we need to add `.*` before or/and after regexp if we want to match paths like starting with string or ending with string.
**Without**: we need to add `^ and $` if we want to match full param part from start to end. Like we do it when we writing regexps.

First (**With**) looks convenient for defining routes.
Second (**Without**) looks like standard solution, because we always writing regexps with `^ and $` in our code.

So I doubt any of the decision to choose the default behavior.

**Comment by rkrx** [comment]
Can you give me a brief example in what situation the _with_Argument would apply. I doubt that you will ever need it.

**Comment by mindplay-dk** [comment]
I'd like to know too, in what specific case is this useful?

**Comment by baryshev** [comment]
Now ^ and $ added by default.
